permalink: pretty
timezone: America/Sao_Paulo

markdown: CommonMark

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["table", "strikethrough"]

defaults:
  - scope:
      path: "textos"
      type: "posts"
    values:
      layout: "texto"
